client/js/components/common/drop_zone.spec.js
client/js/components/common/drop_zone_index.spec.js
client/js/components/common/mapped_image.jsx
client/js/components/common/mapped_image.spec.js
client/js/components/common/matching.jsx
client/js/components/common/matching.spec.js
client/js/components/common/progress_dropdown.jsx
client/js/components/common/radio_button.spec.js
client/js/components/index.jsx
client/js/components/index.spec.js
client/js/components/main/assessment.jsx
client/js/components/main/assessment.spec.js
client/js/components/main/start.spec.js
client/js/components/post_nav/full_post_nav.jsx
client/js/parsers/qti1/parser.spec.js
client/js/parsers/qti1/qti.js
client/js/parsers/qti1/qti.spec.js
client/js/reducers/assessment.spec.js

David had mentioned we should stop just pushing to master. Here are some fixes for the QTI1 parser, and its specs.

Triage tests

---

README.md
client/html/layouts/application.html
client/js/components/assessments/item.jsx
client/js/components/main/assessment.jsx
client/js/components/main/assessment.spec.js
client/js/parsers/qti1/selectors.js
client/js/reducers/progress.js
client/js/reducers/settings.js

Assessment will render a basic question

 Refactor assessment

---

README.md
client/html/layouts/application.html
client/js/actions/assessment_progress.js
client/js/components/assessments/item.jsx
client/js/components/main/assessment.jsx
client/js/components/main/assessment.spec.js
client/js/parsers/qti1/selectors.js
client/js/reducers/jwt.spec.js
client/js/reducers/progress.js
client/js/reducers/progress.spec.js

Uses question_per_section to select how many questions to display at a time. Will page through questions, and disable previous and next buttons when next or previous questions are not available.

Show all questions

---

client/js/actions/assessment_progress.js
client/js/components/assessments/universal_input.jsx
client/js/components/assessments/universal_input.spec.js
client/js/components/common/radio_button.jsx
client/js/components/main/assessment.jsx
client/js/components/main/assessment.spec.js
client/js/reducers/jwt.spec.js
client/js/reducers/progress.js
client/js/reducers/progress.spec.js

Some answer inputs should only allow one selected answer at a time. I added a flag to the selectAnswer action that will determine if more than one answer is allowed to be selected.

Exclusive Answer Flag

---

client/js/components/assessments/universal_input.jsx

Removes unused code, and changes variable names to be more clear

Remove unused code from universal input 

---

client/js/components/assessments/universal_input.jsx
client/js/components/common/feedback_icon.jsx
client/js/components/common/feedback_icon.spec.js
client/js/components/common/radio_button.jsx

Removes getFeedbackImage from radio_button.jsx 
Creates FeedbackIcon component so it can be reused by other answer types 
Changes displayCorrect and displayIncorrect props to gradeState

Refactor radio button

---

client/styles/components/_components.answers.scss
client/styles/components/_components.assessment-navigation.scss
client/styles/components/_components.confidence-map.scss
client/styles/components/_components.question-prompt.scss
client/styles/tools/_tools.mixins.scss

Adds fixes for collapsing nav when previous button is not present
Fixes next button arrow

Updated Styles

---

client/js/routes.jsx

Just to show you what caused my problem...you probably want to delete that declaration instead of just commenting it out.

remove redundant component that broke webpack

---

client/js/components/common/radio_button.jsx
client/js/components/common/radio_button.spec.js
client/styles/components/_components.answers.scss

Wrap answer content and radio button  in label
Change radio button border from label element to a div

Fix radio markup

---

client/js/components/assessments/item.jsx
client/js/components/assessments/universal_input.jsx
client/js/components/assessments/universal_input.spec.js
client/js/components/common/checkbox.jsx
client/js/components/common/checkbox.spec.js
client/js/reducers/progress.js
client/styles/components/_components.answers.scss

Adds multiple answer question 
Cleans up universal input

Multiple answer question

---

client/js/components/assessments/item.jsx
client/js/components/assessments/universal_input.jsx
client/js/components/common/radio_button.jsx
client/js/components/main/assessment.jsx
client/js/components/main/assessment.spec.js
client/js/middleware/qbank.js
client/js/parsers/clix/parser.js
client/js/parsers/clix/parser.spec.js
client/js/reducers/progress.js
client/js/reducers/progress.spec.js

Display Item and answer input components display feedback

Item feedback

---

client/js/components/assessments/item.jsx
client/js/components/assessments/item.spec.js
client/js/components/main/assessment.spec.js

Remove item title from being rendered per MIT request

Don't render item title

---

client/js/components/assessments/loading.jsx
client/js/components/assessments/loading.spec.js
client/js/locales/en.js

Adds string localization loading message

Localize loading screen message

---

client/js/middleware/qbank.js

Handle check answer with empty text box

fix empty text area submit bug

---

client/js/components/assessments/universal_input.jsx
client/styles/components/_components.answers.scss

* Adds two columns of answers 

Reduce whitespace

---

client/js/middleware/qbank.js

Qbank can't handle emtpy multi part uploads, so this adds a check for content before we post to qbank

Audio upload submit

---

client/js/components/assessments/universal_input.jsx
client/js/middleware/qbank.js
client/js/parsers/qti2/qti.js

Adds numerical input question type 

Numerical input

---

README.md
client/html/layouts/application.html
client/js/components/assessments/item.jsx
client/js/components/assessments/universal_input.jsx
client/js/components/common/audio_upload.jsx
client/js/components/common/audio_upload.spec.js
client/js/components/common/recorder.jsx
client/js/reducers/settings.js

Adds setting to control audio recorder timeout 

Audio timer

---

client/js/components/assessments/item.jsx
client/js/locales/en.js

Removes question prompt from assessment item, per MIT request

remove question prompt

---

client/js/components/assessments/universal_input.jsx
client/js/components/common/file_upload.jsx
client/js/components/common/file_upload.spec.js
client/js/locales/en.js
client/styles/components/_components.answers.scss

Adds styles to file_upload question type

File upload

---

client/js/components/assessments/universal_input.jsx
client/js/middleware/qbank.js
client/js/parsers/clix/clix.js

Numerical input question type should display 'Check Answer' text instead of 'Save Answer'

fix numerical input should display check answer text

---

client/package.json

update package.json with video.js dependency

---

README.md
client/html/layouts/application.html
client/js/components/assessments/check_button.jsx
client/js/components/assessments/nav_buttons.jsx
client/js/components/assessments/three_button_nav.jsx
client/js/components/common/button.jsx
client/js/components/main/assessment.jsx
client/js/locales/en.js
client/js/parsers/clix/selectors.js
client/js/parsers/qti2/selectors.js
client/js/selectors/assessment.js
client/styles/components/_components.assessment-navigation.scss

Disabled transitions for visibility.

Added 3-button nav, extracting logic for prev/check/next.

---

client/js/locales/hi.js
client/js/locales/locales.js
client/js/locales/te.js

Adds partial translations for telugu and hindi

add translations

---

client/js/components/assessments/universal_input.jsx
client/js/components/common/sentence_sandbox.jsx
client/js/middleware/qbank.js
client/js/parsers/clix/selectors.js

* Addresses pivotal tracker story #128146381
* Changes moveable words sandbox 'check answer' text to 'save file' 
* Sends most recently recorded audio file back to qbank

Upload mw sandbox audio

---

client/js/middleware/qbank.js

* Extracts duplicated api code to a single method
* Adds default qbank headers

Send qbank locale

---

client/js/actions/assessment.js
client/js/actions/locale.js
client/js/components/index.jsx
client/js/locales/en.js
client/js/locales/he.js
client/js/locales/hi.js
client/js/locales/locales.js
client/js/locales/te.js
client/js/reducers/index.js
client/js/reducers/locale.js
client/js/selectors/localize.js

Report available locales to parent window, and allow parent to dynamically set the locale

---

client/js/components/common/fill_the_blank/fill_the_blank.jsx
client/js/components/common/fill_the_blank/fill_the_blank_word_chain.jsx
client/styles/components/_components.word-box.scss

Switch back to the old styles

---

client/js/components/index.jsx

Support being an iframe in an iframe

---

client/js/actions/assessment_progress.js
client/js/actions/media_analytics.js
client/js/middleware/api.js
client/js/middleware/api.spec.js
client/js/middleware/assessment_loader.spec.js
client/js/middleware/qbank.js
client/js/middleware/qbank_analytics.js
client/js/store/configure_store.js

Add analytics middleware and actions

---

client/js/utils/communication_handler.js

Fix messages

---

client/js/actions/assessment_progress.js
client/js/actions/media_analytics.js
client/js/components/assessments/item.jsx
client/js/components/assessments/universal_input.jsx
client/js/components/common/audio_upload.jsx
client/js/components/common/audio_upload.spec.js
client/js/components/common/recorder.jsx
client/js/components/common/sentence_sandbox.jsx
client/js/components/main/assessment.jsx
client/js/middleware/analytics.js
client/js/middleware/api.js
client/js/middleware/api.spec.js
client/js/middleware/assessment_loader.spec.js
client/js/middleware/middleware_request.js
client/js/middleware/qbank_analytics.js
client/js/store/configure_store.js

Add analytics to all of the audio/video tags

---

client/js/components/assessments/universal_input.jsx
client/js/parsers/clix/clix.js
client/js/parsers/clix/selectors.js

Survey question type 'check answer' button should display text 'Save Answer' instead of 'Check Answer'

fix survey question text

---

client/js/middleware/qbank.js

Api locale headers were not being sent with qbank get requests, this makes sure that they are sent with every request to ensure we get the correct language.

Locale questions

---

client/package.json
client/yarn.lock

Updates s3-website to fix deploy

---

client/js/_author/components/assessments/assessment_items.jsx
client/js/_author/components/assessments/new_item_form.jsx
client/js/_author/components/assessments/question_types/_question.jsx
client/js/_author/components/assessments/question_types/audio_upload.jsx
client/js/_author/components/assessments/question_types/file_upload.jsx
client/js/_author/components/assessments/question_types/multiple_choice.jsx
client/js/_author/components/assessments/question_types/question_common/feedback.jsx
client/js/_author/components/assessments/question_types/question_common/single_feedback.jsx
client/js/constants/genus_types.js
client/styles/_author/partials/_file-upload.scss

Adds support for Audio Upload question type
Adds support for Generic Upload question type
Adds constants file to define genus types in one place

Add file question support

---

client/js/_author/components/assessments/question_types/multiple_choice.jsx

Makes sure that question exists before putting a value on it

---

client/js/_author/components/assessments/_edit_assessment.jsx
client/js/_author/components/assessments/assessment_form.jsx

Fixes a few bugs associated with redirecting from the new assessment screen to the edit screen

Fix redirect issues

---

client/js/_author/components/bank_navigation/bank_list_header.jsx
client/js/_author/components/bank_navigation/bank_list_item.jsx
client/js/_author/components/bank_navigation/navigation_bar_content.jsx

change name and moves import

---

client/js/_author/components/assessments/question_types/_question.jsx
client/js/_author/components/assessments/question_types/multiple_choice.jsx
client/js/_author/components/assessments/question_types/multiple_choice_option.jsx
client/js/_author/components/assessments/question_types/question_common/settings.jsx
client/js/_author/reducers/items.js
client/js/middleware/qbank.js

This fixes deleting, toggles reOrdering, and hides the re-arrange options if you can't re-order. Re-ordering should work, but the back-end is not using the order field like it should. waiting to hear back from cole on that one.

Better updates

---

client/js/_author/components/assessments/_edit_assessment.jsx

https://www.pivotaltracker.com/story/show/137833741

Adds confirmation to delete

---

client/js/_author/components/assessments/navigation_bar_content.jsx

https://www.pivotaltracker.com/story/show/137834749

fixes the back button

---

client/js/_author/components/assessments/question_types/_question.jsx
client/js/_author/components/assessments/question_types/multiple_choice.jsx
client/js/_author/components/assessments/question_types/multiple_choice_option.jsx

https://www.pivotaltracker.com/story/show/137833663

hides stuff if inactive

---

client/js/_author/reducers/items.js
client/js/middleware/qbank.js

Makes feedback work

---

client/js/_author/components/bank_navigation/bank_list_item.jsx

show if editable delete

---

client/js/_author/components/assessments/_edit_assessment.jsx
client/js/_author/components/assessments/editable_item.jsx

fixes the refresh in edit assessment

---

client/js/_author/components/assessments/_edit_assessment.jsx
client/js/_author/components/assessments/_new_assessment.jsx
client/js/_author/components/assessments/assessment_form.jsx

if not titled assessment, doesn't show questions

---

client/js/_author/components/assessments/_edit_assessment.jsx
client/js/_author/components/assessments/question_types/_question.jsx
client/js/_author/components/assessments/question_types/question_common/settings.jsx

checkboxes for only multiple choice for now

---

.github/PULL_REQUEST_TEMPLATE.md

Mostly this was just annoying, and ignored

---

client/js/_author/components/assessments/navigation_bar_content.spec.jsx

nav bar content spec

---

.travis.yml
README.md
client/config/karma.js
client/package.json
client/yarn.lock
package.json

DEATH TO COVERALLS!

---

client/js/_author/components/assessments/new_item_form.jsx
client/js/constants/language_types.js
client/js/constants/question_types.js
client/js/middleware/qbank.js
client/js/middleware/serialization/qbank/serializers/base.js
client/js/middleware/serialization/qbank/serializers/factory.js

Fixes issues with adding a new question

Serialize and deserialize new questions

---

client/js/_author/components/assessments/new_item_form.jsx

This fixes making questions that aren't multiple choice

Fix add item

---

client/js/_author/reducers/assessment_items.js
client/js/_author/reducers/items.js
client/js/middleware/qbank.js

updates item creation and update

---

client/js/_author/components/assessments/question_types/_question.jsx
client/js/_author/components/assessments/question_types/question_common/text.jsx
client/js/_author/components/common/oea_editor.jsx
client/js/_author/components/common/tiny_wrapper.jsx
client/js/_author/reducers/uploaded_assets.js
client/js/actions/qbank/assets.js
client/js/middleware/serialization/qbank/serializers/base.js
client/js/middleware/serialization/qbank/serializers/multiple_choice.js

Fixes image uploads

---

client/js/_author/components/assessments/question_types/_question.jsx
client/js/_author/components/assessments/question_types/multiple_choice.jsx
client/js/_author/components/assessments/question_types/multiple_choice_option.jsx
client/js/_author/components/assessments/question_types/question_common/option_checkbox.jsx
client/js/_author/components/assessments/question_types/question_common/settings.jsx
client/js/constants/genus_types.js
client/js/constants/question_types.js
client/js/middleware/serialization/qbank/deserializers/factory.js
client/js/middleware/serialization/qbank/serializers/base.js
client/js/middleware/serialization/qbank/serializers/factory.js
client/js/middleware/serialization/qbank/serializers/multiple_answer.js
client/js/middleware/serialization/qbank/serializers/survey.jsx

Multi selection

---

client/js/_author/components/assessments/question_types/multiple_choice_option.spec.jsx
client/js/_author/components/assessments/question_types/question_common/option_checkbox.spec.jsx
client/js/_author/components/bank_navigation/bank_list_item.jsx

Fixed broken css and added spec file for option_checkbox

Spec branch

---

client/js/middleware/serialization/qbank/serializers/multiple_choice.js

https://www.pivotaltracker.com/story/show/137833759

Makes sure bad data isn’t going up

---

client/js/_author/components/assessments/question_types/multiple_choice.jsx
client/js/_author/components/assessments/question_types/question_common/feedback.jsx

https://www.pivotaltracker.com/story/show/137833727

Hides incorrect feedback on reflection questions

---

client/js/middleware/serialization/qbank/serializers/multiple_choice.js

scrubbing choices was a mistake

---

client/js/middleware/serialization/qbank/serializers/multiple_choice.js

Makes sure you can swap the order on one and zero

fixes order bugs

---

client/js/_author/components/assessments/question_types/audio_upload.jsx
client/js/middleware/serialization/qbank/serializers/audio_upload.js

* Makes Audio Upload question not allow setting the audio time limit to greater than the max setting 
* Makes the Audio Upload question time limit default to max time

Fix audio upload

---

client/js/middleware/serialization/qbank/deserializers/factory.js
client/js/middleware/serialization/qbank/deserializers/file_upload.js
client/js/middleware/serialization/qbank/serializers/factory.js
client/js/middleware/serialization/qbank/serializers/file_upload.js

Adds file upload Serializer & Deserializer

Fix File Upload

---

client/html/layouts/partials/_head.html
client/js/_author/components/bank_navigation/bank_list_item.jsx

fixes &bank=

---

client/js/_author/components/assessments/question_types/_question.jsx
client/js/_author/components/assessments/question_types/question_common/settings.jsx
client/js/middleware/serialization/qbank/serializers/multiple_choice.js

Fixes reOrder for other question types

---

client/js/middleware/serialization/qbank/serializers/audio_upload.js

* Fixes audio question serialization

Fix audio question serialization

---

client/js/_author/components/assessments/preview_assessment.jsx
client/js/_author/components/assessments/preview_container.jsx
client/js/_author/components/assessments/question_types/_question.jsx
client/js/_author/components/assessments/question_types/preview_question.jsx
client/js/_author/components/assessments/question_types/question_common/header/default.jsx

Inline previewing of questions

Previewering

---

client/js/_author/components/assessments/new_item_form.jsx
client/js/_author/components/assessments/new_item_form.spec.jsx

The death of language

---

client/js/_author/components/assessments/_new_assessment.jsx
client/js/_author/components/assessments/assessment_form.jsx

allows going back from new assessment

---

client/js/_author/components/assessments/_edit_assessment.jsx
client/js/_author/components/assessments/_new_assessment.jsx
client/js/_author/components/bank_navigation/_bank_navigator.jsx
client/js/_author/components/bank_navigation/breadcrumb.jsx
client/js/_author/reducers/bank_navigation.js
client/js/_author/reducers/banks.js
client/js/actions/qbank/banks.js

refreshed now allow for back button

---

client/js/_author/reducers/banks.js

Makes sure stuff isn’t breaking

---

client/config/karma.js
client/js/_author/components/assessments/navigation_bar_content.jsx
client/js/_author/components/bank_navigation/bank_list_item.spec.jsx
client/js/_author/components/common/oea_editor.spec.jsx
client/specs_support/fixtures/new_content_id/stream
client/specs_support/fixtures/old_content_id/stream

Fixes spec warnings

---

client/js/_author/components/assessments/question_types/moveable_word_sentence/word_type_dropdown.jsx
client/js/middleware/serialization/qbank/serializers/moveable_word_sentence.js
client/styles/_author/partials/_moveable-words.scss

Makes the 'part of speech selection thing' behave correctly, and allows users to set answer orders back to null

Word sentence things

---

client/js/_author/components/assessments/question_types/_question.jsx
client/js/_author/components/assessments/question_types/movable_word_sentence/option.jsx
client/js/middleware/serialization/qbank/deserializers/movable_word_sentence.js
client/js/middleware/serialization/qbank/serializers/movable_word_sentence.js
client/styles/_author/partials/_movable-words.scss

Just fixes some things for kirky

Manage choices

---

client/html/layouts/partials/_head.html
client/js/_author/components/assessments/preview_assessment.jsx
client/js/_author/components/assessments/preview_assessment.spec.jsx
client/js/_author/components/assessments/preview_container.jsx
client/js/_author/components/assessments/preview_container.spec.jsx

* Updates full assessment preview to support configuring player settings

Update assessment preview

---

client/html/styles.html
client/styles/_author/partials/_buttons.scss
client/styles/_author/partials/_movable-words.scss

html/css in the styles.html are now correct for fill in the blank

Fixed Fill in the blank input and added a class for Nick to use

---

client/js/middleware/serialization/qbank/serializers/movable_words_sandbox.js

* Fixes options not persisting

Fix Moveable Word Sandbox Options

---

client/js/_author/components/assessments/question_types/_question.jsx
client/js/_author/components/assessments/question_types/movable_word_sentence/movable_word_sentence.jsx

https://www.pivotaltracker.com/story/show/142107601

---

client/js/_author/components/assessments/new_item_form.jsx

* New Item Form defaults to MC

Fixes new item form

---

client/js/_author/components/_index.jsx
client/js/_author/components/bank_navigation/_bank_navigator.jsx
client/js/_author/components/bank_navigation/bank_list.jsx
client/js/_author/components/bank_navigation/bank_list_item.jsx
client/js/_author/components/bank_navigation/bank_list_item.spec.jsx
client/js/_author/reducers/index.js
client/js/_author/reducers/media.js
client/js/actions/qbank/banks.js
client/js/constants/genus_types.js
client/js/middleware/qbank.js

Reducer for different types of media, images, audio, video

getting all media and putting in reducer

---

client/js/middleware/serialization/qbank/deserializers/image_sequence.js
client/js/middleware/serialization/qbank/serializers/image_sequence.js

* Correctly serializes answers for image sequence questions

Fix Image sequence ordering

---

client/js/_author/components/assessments/question_types/movable_words_sandbox/option.jsx
client/js/_author/components/assessments/question_types/preview_question.jsx

* Adds question preview support for image sequence and moveable words sandbox
* Changes moveable word sandbox wort type 'N/A' to 'other', per MIT request

Fix question preview 

---

client/js/middleware/serialization/qbank/serializers/image_sequence.js

* Image sequence should send up empty array of choiceIds for incorrect answer

send up empty choiceIds array for incorrect answer

---

client/js/_author/components/bank_navigation/_bank_navigator.jsx
client/js/_author/components/bank_navigation/bank_list.jsx
client/js/_author/components/bank_navigation/bank_list.spec.jsx
client/js/_author/selectors/bank_navigator.js

* Handle banks that have no assessments or children banks

Fix no assessments spinning

---

client/js/_author/components/assessments/question_types/preview_question.jsx

* Fixes word coloring on single question preview for moveable word questions

Serialize moveable question types for question preview

---

client/js/_author/components/assessments/question_types/image_sequence/add_image.jsx
client/js/_author/components/assessments/question_types/image_sequence/image_option.jsx
client/js/_author/locales/en.js

fixes locales stff

---

client/js/_author/components/assessments/question_types/multiple_choice/multiple_choice.jsx
client/js/_author/components/assessments/question_types/multiple_choice/multiple_choice.spec.jsx

when you click the new choice, the new choice button is hidden in the new choice they just created is done.

makes it so you can only add one choice at a time

---

client/js/_author/components/bank_navigation/_bank_navigator.jsx
client/js/_author/components/bank_navigation/bank_assessment.jsx
client/js/_author/components/bank_navigation/bank_folder.jsx
client/js/_author/components/bank_navigation/bank_list.jsx
client/js/_author/components/bank_navigation/buttons/delete_button.jsx
client/js/_author/components/bank_navigation/buttons/edit_button.jsx
client/js/_author/components/bank_navigation/buttons/embed_button.jsx
client/js/_author/components/bank_navigation/buttons/preview_button.jsx
client/js/_author/components/bank_navigation/buttons/publish_button.jsx
client/js/_author/components/bank_navigation/list_item.jsx
client/styles/_author/partials/_dashboard.scss

make buttons in bank navigation work by keyboard

Accessible buttons

---

client/js/_author/components/bank_navigation/buttons/preview_button.jsx

when you click preview from the banks list it opens in a new window

open in new window

---

client/js/_author/components/bank_navigation/bank_assessment.jsx
client/styles/_author/partials/_dashboard.scss

adds loader when you click delete

---

.eslintrc.yml
client/js/_author/components/bank_navigation/bank_assessment.jsx
client/package.json
client/yarn.lock

Actually fix hound

---

client/js/constants/network.js
client/js/middleware/qbank.js

Initial upload of audio and video for question stem

Bc not broken media

---

client/js/_author/components/bank_navigation/empty_bank_list.jsx

better wording

---

client/js/_author/components/common/oea_editor.jsx

* Fixes new media video playing bug

Fix new media bug

---

client/js/_author/components/assessments/question_types/_question.jsx
client/js/_author/components/common/oea_editor.jsx
client/js/_author/components/common/upload_modal/media_table.jsx

* Fixes no media placeholder bug
* Removes transcript markup from editor

MetaData Fixes 

---

client/js/_author/components/common/oea_editor.jsx
client/js/_author/components/common/tiny_wrapper.jsx
client/js/middleware/serialization/qbank/serializers/base.js

Fixes some weird place holder wonkyness

fixes the placeholder

---

client/js/_author/components/common/upload_modal/meta_file_inputs.jsx
client/js/constants/language_types.js
client/js/middleware/qbank.js

* Uses styled file input
* Updates alternative language description and alt-text

Fix metadata

---

client/js/_author/components/assessments/_edit_assessment.jsx
client/js/_author/components/assessments/_new_assessment.jsx
client/js/_author/components/bank_navigation/_bank_navigator.jsx
client/js/_author/components/bank_navigation/_banks_navigator.spec.jsx
client/js/_author/components/common/upload_modal/editor_upload_modal.jsx

cleans state between media upload

---

client/js/middleware/serialization/qbank/serializers/movable_word_sentence.js

fixes feedback

---

client/js/_author/components/assessments/_edit_assessment.jsx
client/js/_author/components/assessments/_edit_assessment.spec.jsx
client/js/_author/components/assessments/_new_assessment.jsx
client/js/_author/components/assessments/_new_assessment.spec.jsx
client/js/_author/components/bank_navigation/_bank_navigator.jsx
client/js/_author/components/bank_navigation/_banks_navigator.spec.jsx
client/js/actions/qbank/items.js
client/js/middleware/qbank.js

Takes the getItems() out of app everywhere because not used.

takes out the getItems() becuase it is not used

---

client/js/_author/components/bank_navigation/_bank_navigator.jsx
client/js/_author/components/bank_navigation/bank_assessment.jsx
client/js/_author/components/bank_navigation/bank_assessment.spec.jsx
client/js/_author/components/bank_navigation/bank_list.jsx
client/js/_author/components/bank_navigation/buttons/publish_button.jsx
client/js/_author/reducers/assessments.js
client/js/actions/qbank/assessments.js
client/js/middleware/qbank.js

Handles double clicking and sync issues

Double clicker

---

client/js/_author/components/assessments/question_types/drag_and_drop/__snapshots__/target_placeholder.spec.jsx.snap
client/js/_author/components/assessments/question_types/drag_and_drop/target_placeholder.spec.jsx

last spec??

---

client/js/_author/components/assessments/question_types/preview_question.jsx
client/js/_author/components/common/oea_editor.jsx
client/js/_author/components/common/tiny_wrapper.jsx
client/js/_author/reducers/items.js
client/styles/_author/partials/_loader.scss

* Fixes not being able to delete entire question stem
* Fixes making requests to malformed url's during question preview
* Handles inserting media errors

Small bug fixes

---

client/js/_author/components/bank_navigation/buttons/__snapshots__/delete_button.spec.jsx.snap
client/js/_author/components/bank_navigation/buttons/__snapshots__/edit_button.spec.jsx.snap
client/js/_author/components/bank_navigation/buttons/__snapshots__/embed_button.spec.jsx.snap
client/js/_author/components/bank_navigation/buttons/__snapshots__/preview_button.spec.jsx.snap
client/js/_author/components/bank_navigation/buttons/__snapshots__/publish_button.spec.jsx.snap
client/js/_author/components/bank_navigation/buttons/delete_button.spec.jsx
client/js/_author/components/bank_navigation/buttons/edit_button.spec.jsx
client/js/_author/components/bank_navigation/buttons/embed_button.spec.jsx
client/js/_author/components/bank_navigation/buttons/preview_button.spec.jsx
client/js/_author/components/bank_navigation/buttons/publish_button.spec.jsx

Spectastic

---

client/js/_author/components/assessments/question_types/image_sequence/_image_sequence.jsx
client/js/_author/components/assessments/question_types/image_sequence/image_order.jsx

cleans up ...props and hides when appropriate

deplat the props and hide not isActive choices

---

client/js/_author/components/common/upload_modal/editor_upload_modal.jsx
client/js/_player/components/assessments/universal_input.jsx

Fixes file upload preview not working

Fix some excessive state transitions

---

client/js/_author/components/assessments/question_types/_question.jsx
client/js/_author/components/assessments/question_types/question_common/header/default.jsx
client/js/_author/reducers/items.js

For length of time while removing item it will show the dot loader.

puts loader if in removing state

---

client/js/_author/components/common/upload_modal/editor_upload_modal.jsx
client/js/_author/components/common/upload_modal/meta_data.jsx
client/js/middleware/qbank.js

adds in citation in metadata

---

client/js/_author/components/assessments/question_types/_question.jsx
client/js/_author/components/assessments/question_types/multiple_choice/multiple_choice.jsx
client/js/_author/components/assessments/question_types/multiple_choice/multiple_choice_option.jsx
client/js/_author/components/assessments/question_types/multiple_choice/multiple_choice_option.spec.jsx
client/js/_author/components/assessments/question_types/multiple_choice/option_feedback.jsx
client/js/_author/components/common/oea_editor.jsx
client/js/actions/qbank/items.js
client/js/middleware/serialization/qbank/deserializers/multiple_answer.js
client/js/middleware/serialization/qbank/deserializers/multiple_choice.js
client/js/middleware/serialization/qbank/serializers/multiple_answer.js
client/js/middleware/serialization/qbank/serializers/multiple_choice.js
client/js/middleware/serialization/serializer_utils.js

* Add support for multi language choices for multiple choice and multiple answer

Choice language

---

client/js/_author/components/assessments/question_types/movable_words_sandbox/movable_words_sandbox.jsx
client/js/_author/components/assessments/question_types/movable_words_sandbox/option.jsx
client/js/middleware/serialization/qbank/deserializers/movable_words_sandbox.js
client/js/middleware/serialization/qbank/deserializers/movable_words_sandbox.spec.js
client/js/middleware/serialization/qbank/serializers/movable_words_sandbox.js
client/js/middleware/serialization/qbank/serializers/movable_words_sandbox.spec.js

* Adds support for mutiple language choices for movable words sandbox

Multi language moveable words sandbox

---

client/js/_author/components/assessments/question_types/_question.jsx
client/js/_author/components/assessments/question_types/movable_word_sentence/movable_word_sentence.jsx
client/js/_author/components/assessments/question_types/movable_word_sentence/option.jsx
client/js/middleware/serialization/qbank/deserializers/movable_word_sentence.js
client/js/middleware/serialization/qbank/deserializers/movable_word_sentence.spec.js
client/js/middleware/serialization/qbank/deserializers/movable_words_sandbox.js
client/js/middleware/serialization/qbank/serializers/movable_word_sentence.js
client/js/middleware/serialization/qbank/serializers/movable_word_sentence.spec.js
client/js/middleware/serialization/serializer_utils.js

* Add multi language support for movable words sentence questions

Nb multi language movable words sentance

---

client/js/_author/components/assessments/question_types/movable_fill_blank/option.jsx
client/js/_author/components/assessments/question_types/movable_word_sentence/option.jsx
client/js/_author/components/assessments/question_types/movable_words_sandbox/option.jsx
client/js/middleware/serialization/qbank/serializers/movable_fill_blank.js
client/js/middleware/serialization/qbank/serializers/movable_word_sentence.js
client/js/middleware/serialization/qbank/serializers/movable_words_sandbox.js
client/js/middleware/serialization/qbank/serializers/movable_words_sandbox.spec.js
client/js/middleware/serialization/serializer_utils.js

* Keeps word type consistent between choices of different languages 
* Fixes adding new options for fill in the blank

Update movable words

---

client/js/_author/components/assessments/question_types/_question.jsx
client/js/middleware/serialization/qbank/serializers/reflection.jsx
client/js/middleware/serialization/qbank/serializers/reflection.spec.jsx

Add multi language support for reflection question types

Fix reflection question types

---

client/js/_author/components/assessments/question_types/drag_and_drop/__snapshots__/drag_area.spec.jsx.snap
client/js/_author/components/assessments/question_types/drag_and_drop/drag_area.jsx
client/js/_author/components/common/upload_modal/meta_data.jsx
client/js/_author/locales/en.js
client/js/_player/actions/communications.js
client/js/middleware/serialization/qbank/deserializers/drag_and_drop.js
client/js/middleware/serialization/qbank/serializers/drag_and_drop.js
client/js/middleware/serialization/qbank/serializers/image_sequence.js
client/js/middleware/serialization/serializer_utils.js

Fixes altText not showing correctly in image sequence and drag and drop

Fix altText 

---

client/js/_author/components/assessments/question_types/drag_and_drop/__snapshots__/target_area.spec.jsx.snap
client/js/_author/components/assessments/question_types/drag_and_drop/target_area.jsx
client/js/_author/components/assessments/question_types/multiple_choice/multiple_choice_option.jsx

pass language

---

README.md

Fixed some markdown errors for README file

fix: README.md markdown errors
